-- auto-generated definition
create table avatar_picture
(
    id           bigint generated by default as identity
        primary key,
    content_size bigint       not null,
    content_type varchar(255) not null,
    name         varchar(255) not null,
    url          text         not null
);

alter table avatar_picture
    owner to postgres;

-- auto-generated definition
create table roles
(
    id      bigint generated by default as identity
        primary key,
    role    varchar(255),
    user_id bigint
        constraint fk97mxvrajhkq19dmvboprimeg1
            references users
);

alter table roles
    owner to postgres;

-- auto-generated definition
create table users
(
    id                bigint generated by default as identity
        primary key,
    email             varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password          varchar(255),
    username          varchar(255) not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique,
    avatar_picture_id bigint
        constraint ukksdb6pb4x9dg2ayjcgq2w8qrh
            unique
);

alter table users
    owner to postgres;

