version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: storage

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: filestorage
      MINIO_ROOT_PASSWORD: filestorage
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    hostname: localhost

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./src/main/resources/datasource:/etc/grafana/provisioning/datasource

volumes:
  postgres-data:
  minio-data:
